apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-data
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: {{ .Values.pv.storage }}
  accessModes:
    - {{ .Values.pv.accessModes }}
  hostPath:
    path: {{ .Values.pv.hostPath }}
