apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data-claim
  namespace: {{ .Values.namespace }}
spec:
  resources:
    requests:
       storage: {{ .Values.pvc.storage }}
  accessModes:
    - {{ .Values.pvc.accessModes }}
