apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.db.service.type }}
  ports:
  - port: {{ .Values.db.service.port }}
    targetPort: {{ .Values.db.container.port }}
  selector:
    tier: {{ .Values.db.tier }}

