namespace: kanban-board


ui:
  
  replicaCount: 1
  tier: ui
  image:
    repository: str24/kanban-ui
    pullPolicy: IfNotPresent
    tag: "latest"
  container:
    name: kanban-board-ui
    port: 80
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""


  service:
    type: NodePort
    nodePort: 32009
    port: 80


