apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingress.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: ca-issuer
spec:
  rules:
    - host: kanban-board
      http:
        paths:
          - path: /api/
            pathType: Prefix
            backend:
              service:
                name: kanban-board-app-svc
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: kanban-board-ui-svc
                port:
                  number: 80
                    #  tls:
                    # - hosts: 
                    #     - "kanban-board"
                    #     secretName: kanban-board
