apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
  - port: {{ .Values.ui.service.port }}
    targetPort: {{ .Values.ui.container.port }}
    nodePort: {{ .Values.ui.nodePort }}
  selector:
    tier: {{ .Values.ui.tier }}

